#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# If fish is default SHELL install fisher
if [ "$SHELL" = "/usr/bin/fish" ]; then
  if ! [ -f ~/.config/fish/functions/fisher.fish ]; then
    echo "fish shell found: Install fisher"
    fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
  fi
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping nVim"
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  sudo apt install python-pip python3-pip
  sudo pip3 install --upgrade neovim
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
